import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const contract = readFileSync(
  resolve(import.meta.dirname, "../../docs/contracts/api.openapi.yaml"),
  "utf8",
);
const generated = readFileSync(resolve(import.meta.dirname, "../src/generated/api.ts"), "utf8");

const forbiddenGeneratedSettingsPath =
  /(?:RuntimeDestination|RuntimeSettings): \{(?:(?!\n    \};)[\s\S])*?\b(?:root|mediaRoot|mediaRoots)\??:/;
const forbiddenContractPath = /(^|\n)\s+(root|mediaRoot|mediaRoots):/;

describe("generated API contract", () => {
  it("contains the checked-in response schemas and operations", () => {
    expect(generated).toContain("This file was auto-generated by openapi-typescript");
    for (const operation of [
      "listMedia",
      "browseMediaTree",
      "getMedia",
      "getProject",
      "createDetection",
      "createExport",
      "getJob",
    ]) {
      expect(contract).toContain(`operationId: ${operation}`);
      expect(generated).toContain(`${operation}:`);
    }
    for (const schema of ["FolderPage", "RuntimeSettings", "DetectionJob"]) {
      expect(generated).toContain(`${schema}:`);
    }
  });

  it("models scene changes as points without active confidence fields", () => {
    expect(contract).toContain("DetectionPointCandidate");
    expect(contract).toContain("pointMs");
    expect(generated).toContain("DetectionPointCandidate");
    expect(generated).toContain("pointMs: number");
    expect(contract).not.toContain("confidence");
    expect(generated).not.toContain("confidence");
  });

  it("does not expose deployment filesystem paths in browser settings schemas", () => {
    expect(generated).toContain("SettingsResponse");
    expect(forbiddenGeneratedSettingsPath.test(generated)).toBe(false);
    expect(forbiddenContractPath.test(contract)).toBe(false);
  });

  it("closes the SettingsUpdate object at the top level", () => {
    expect(contract).toContain(
      "    SettingsUpdate:\n      type: object\n      additionalProperties: false\n      required: [revision, settings]",
    );
  });

  it("detects forbidden path fields with positive controls", () => {
    expect(
      forbiddenGeneratedSettingsPath.test("RuntimeDestination: {\n      root?: string;\n    };"),
    ).toBe(true);
    expect(
      forbiddenGeneratedSettingsPath.test(
        "RuntimeSettings: {\n      mediaRoots: string[];\n    };",
      ),
    ).toBe(true);
    expect(forbiddenContractPath.test("properties:\n        root: { type: string }")).toBe(true);
  });
});
