import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const contract = readFileSync(
  resolve(import.meta.dirname, "../../docs/contracts/api.openapi.yaml"),
  "utf8",
);
const generated = readFileSync(resolve(import.meta.dirname, "../src/generated/api.ts"), "utf8");

describe("generated API contract", () => {
  it("contains the checked-in response schemas and operations", () => {
    expect(generated).toContain("This file was auto-generated by openapi-typescript");
    for (const operation of [
      "listMedia",
      "browseMediaTree",
      "getMedia",
      "getProject",
      "createDetection",
      "createExport",
      "getJob",
    ]) {
      expect(contract).toContain(`operationId: ${operation}`);
      expect(generated).toContain(`${operation}:`);
    }
    for (const schema of ["FolderPage", "RuntimeSettings", "DetectionJob"]) {
      expect(generated).toContain(`${schema}:`);
    }
  });
});
