-- Generated by Agent E (E01). Apply in numeric order.
CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  owner_login TEXT NOT NULL,
  revision INTEGER NOT NULL CHECK (revision > 0),
  document_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS projects_owner_updated ON projects (owner_login, updated_at DESC);
